theme: jekyll-theme-cayman
title: Les carnets de bord du Challenge Data 5
description: Revivez l'expérience d'ouverture des données publiques avec le récit des étudiants de Sciences Po Saint-Germain-En-Laye
